### ISSUE TITLE
Hand-Rolled EdDSA Implementation in SGX Verification Critical-Path

### ISSUE THREAD

**Issue by DavidBuchanan314** [snowhaze/zka-sgx#1]
As a user of your service, I want to verify the authenticity of your SGX enclave.

To do this, I must trust the implementation of your verifier script.

Please don't do this:
https://github.com/snowhaze/zka-sgx/blob/b249a247eaafdfe2f187737bb4a2f0e0e19f5e83/verify.py#L19-L112

I don't have the time nor qualifications to audit a hand-rolled EdDSA implementation. Please just call into a trusted library implementation (e.g. PyNaCl).

I'm not saying there are any bugs or backdoors in this implementation, but the issue is that I can't easily verify that (which defeats the entire purpose of this script/repo!).

**Comment by DavidBuchanan314** [comment]
Side note, if anyone else wants to verify the SSL certs embedded in the script, you can find the originals here:

https://www.tbs-x509.com/USERTrustRSACertificationAuthority.crt

https://secure.globalsign.net/cacert/Root-R1.crt

(those should probably be added as code comments, to aid independent verification)

**Comment by snowhaze** [comment]
Hi, First of all, thank you for the suggestion regarding the certificates. We will be adding references to https://support.sectigo.com/articles/Knowledge/Sectigo-Intermediate-Certificates and https://support.globalsign.com/ca-certificates/root-certificates/globalsign-root-certificates

As for the Ed25519 implementation:
The main issue is that we support use cases where the script must be self-contained. Keep in mind that auditing an Ed25519 implementation would essentially mean comparing it to the version we used as a basis here. With the remarks, we expect this to be significantly less effort than checking the rest of the script. That being said, a reflexive distrust of any crypto-code is understandable and something we would like to encourage. Therefore, we will be adding a command-line option to use PyNaCl for the signature verification. According to our tests, this also has the benefit of running roughly 1.5 orders of magnitude faster.

I hope this addresses your concerns, and thank you for bringing them up again.

**Comment by Peyman1998Cheraghi** [comment]
> As a user of your service, I want to verify the authenticity of your SGX enclave.
> 
> To do this, I must trust the implementation of your verifier script.
> 
> Please don't do this:
> 
> [zka-sgx/verify.py](https://github.com/snowhaze/zka-sgx/blob/b249a247eaafdfe2f187737bb4a2f0e0e19f5e83/verify.py#L19-L112)
> 
> Lines 19 to 112 in [b249a24](/snowhaze/zka-sgx/commit/b249a247eaafdfe2f187737bb4a2f0e0e19f5e83)
> 
>  class ed25519: 
>  	"""adapted from https://ed25519.cr.yp.to/python/ed25519.py: 
>  	- replaced / with // (original was for python2) 
>  	- replaced ''.join() with bytes() (original was for python2) 
>  	- removed unnecessary ord() and chr() (original was for python2) 
>  	- added some self. and self, (original was a separate module instead of a class) 
>  	- moved all constant initializations to __init__ (original was a separate module instead of a class) 
>  	- moved computations which don't depend on pk to __init__ (for performance) 
>  	- replaced expmod with the builtin pow (for performance) 
>  	- made checkvalid return a bool instead of throwing an exception 
>  	- tweaked indentation (to fit with this file) 
>  	- removed unused functions 
>  	- removed import hashlib""" 
>   
>  	def __init__(self,s,m): 
>  		self.b = 256 
>  		self.q = 2**255 - 19 
>  		self.l = 2**252 + 27742317777372353535851937790883648493 
>  		self.d = -121665 * self.inv(121666) 
>  		self.I = pow(2,(self.q-1)//4,self.q) 
>  		self.By = 4 * self.inv(5) 
>  		self.Bx = self.xrecover(self.By) 
>  		self.B = [self.Bx % self.q,self.By % self.q] 
>   
>  		if len(s) != self.b//4: raise Exception("signature length is wrong") 
>  		self.m = m 
>  		self.R = self.decodepoint(s[0:self.b//8]) 
>  		S = self.decodeint(s[self.b//8:self.b//4]) 
>  		self.Rpoint = self.encodepoint(self.R) 
>  		self.verifier = self.scalarmult(self.B,S) 
>   
>  	def H(self,m): 
>  		return hashlib.sha512(m).digest() 
>   
>  	def inv(self,x): 
>  		return pow(x,self.q-2,self.q) 
>   
>  	def xrecover(self,y): 
>  		xx = (y*y-1) * self.inv(self.d*y*y+1) 
>  		x = pow(xx,(self.q+3)//8,self.q) 
>  		if (x*x - xx) % self.q != 0: x = (x*self.I) % self.q 
>  		if x % 2 != 0: x = self.q-x 
>  		return x 
>   
>  	def edwards(self,P,Q): 
>  		x1 = P[0] 
>  		y1 = P[1] 
>  		x2 = Q[0] 
>  		y2 = Q[1] 
>  		x3 = (x1*y2+x2*y1) * self.inv(1+self.d*x1*x2*y1*y2) 
>  		y3 = (y1*y2+x1*x2) * self.inv(1-self.d*x1*x2*y1*y2) 
>  		return [x3 % self.q,y3 % self.q] 
>   
>  	def scalarmult(self,P,e): 
>  		if e == 0: return [0,1] 
>  		Q = self.scalarmult(P,e//2) 
>  		Q = self.edwards(Q,Q) 
>  		if e & 1: Q = self.edwards(Q,P) 
>  		return Q 
>   
>  	def encodepoint(self,P): 
>  		x = P[0] 
>  		y = P[1] 
>  		bits = [(y >> i) & 1 for i in range(self.b - 1)] + [x & 1] 
>  		return bytes([sum([bits[i * 8 + j] << j for j in range(8)]) for i in range(self.b//8)]) 
>   
>  	def bit(self,h,i): 
>  		return (h[i//8] >> (i%8)) & 1 
>   
>  	def Hint(self,m): 
>  		h = self.H(m) 
>  		return sum(2**i * self.bit(h,i) for i in range(2*self.b)) 
>   
>  	def isoncurve(self,P): 
>  		x = P[0] 
>  		y = P[1] 
>  		return (-x*x + y*y - 1 - self.d*x*x*y*y) % self.q == 0 
>   
>  	def decodeint(self,s): 
>  		return sum(2**i * self.bit(s,i) for i in range(0,self.b)) 
>   
>  	def decodepoint(self,s): 
>  		y = sum(2**i * self.bit(s,i) for i in range(0,self.b-1)) 
>  		x = self.xrecover(y) 
>  		if x & 1 != self.bit(s,self.b-1): x = self.q-x 
>  		P = [x,y] 
>  		if not self.isoncurve(P): raise Exception("decoding point that is not on curve") 
>  		return P 
>   
>  	def checkvalid(self,pk): 
>  		if len(pk) != self.b//8: raise Exception("public-key length is wrong") 
>  		A = self.decodepoint(pk) 
>  		h = self.Hint(self.Rpoint + pk + self.m) 
>  		return self.verifier == self.edwards(self.R,self.scalarmult(A,h)) 
> I don't have the time nor qualifications to audit a hand-rolled EdDSA implementation. Please just call into a trusted library implementation (e.g. PyNaCl).
> 
> I'm not saying there are any bugs or backdoors in this implementation, but the issue is that I can't easily verify that (which defeats the entire purpose of this script/repo!).

Successing from Iran
